services:
  undicitypes:
    image: undicitypes
    build:
      context: node_modules/undici-types
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
